{% set name = "raven-hydro" %}
{% set version = "0.4.0" %}
{% set sha256 = "f9a14114e7516c55ca0b858886d280f3de5504b01800ae182753fc9b9538af35" %}
{% set raven_version = "4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake >=3.26.1
    - make  # [not win]
    - ninja >=1.11.0  # [win]
  host:
    - python
    - hatch-fancy-pypi-readme >=23.1.0
    - hatchling >=1.23.0
    - libnetcdf
    - pip
    - pybind11 >=2.13.0,<3.0
    - scikit-build-core >=0.10
    - setuptools-scm >=8.0
    - zlib
  run:
    - python
    - libnetcdf
    - zlib

test:
  imports:
    - raven_hydro
  requires:
    - pip
    - python
  commands:
    - pip check
    - test -f $PREFIX/bin/raven  # [not win]
    - raven -v

about:
  home: https://raven.uwaterloo.ca
  dev_url: https://github.com/Ouranosinc/raven-hydro
  doc_url: https://raven.uwaterloo.ca/files/v{{ raven_version }}/RavenManual_v{{ raven_version }}.pdf
  doc_source_url: https://raven.uwaterloo.ca/Downloads.html
  license: Apache-2.0 and Artistic-2.0
  license_file:
    - LICENSE
    - RavenHydroFramework/LICENSE
  summary: |
    The Python-based installer for the hydrological modelling framework, Raven,
    developed at the University of Waterloo in Ontario, Canada.

extra:
  recipe-maintainers:
    - Zeitsperre
    - julemai
    - huard
