{% set name = "raven-hydro" %}
{% set version = "4.12.0" %}
{% set sha256 = "d086721efd7993c65ea6c7cd6632cabd17a26f4893393ec66f878c52258d54af" %}
{% set raven_version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11 >=3.0.1,<4.0                 # [build_platform != target_platform]
    - cmake >=3.26.1
    - make  # [not win]
    - ninja >=1.11.0  # [win]
  host:
    - python
    - hatch-fancy-pypi-readme >=25.1.0
    - hatchling >=1.27.0
    - libnetcdf
    - pip
    - pybind11 >=3.0.1,<4.0
    - scikit-build-core >=0.11
    - setuptools-scm >=9.2
    - zlib
  run:
    - python
    - libnetcdf
    - zlib

test:
  imports:
    - raven_hydro
  requires:
    - pip
    - python
  commands:
    - pip check
    - test -f $PREFIX/bin/raven  # [not win]
    - raven -v

about:
  home: https://raven.uwaterloo.ca
  dev_url: https://github.com/Ouranosinc/raven-hydro
  doc_url: https://raven.uwaterloo.ca/files/v{{ raven_version }}/RavenManual_v{{ raven_version }}.pdf
  doc_source_url: https://raven.uwaterloo.ca/Downloads.html
  license: Apache-2.0 and Artistic-2.0
  license_file:
    - LICENSE
    - RavenHydroFramework/LICENSE
  summary: |
    The Python-based installer for the hydrological modelling framework, Raven,
    developed at the University of Waterloo in Ontario, Canada.

extra:
  recipe-maintainers:
    - Zeitsperre
    - julemai
    - huard
