{% set name = "raven-hydro" %}
{% set version = "4.12.1" %}
{% set sha256 = "596e0ef73e0f8a5fbfaee15df138e1217f67c883e505ac2e1600bce6e3adc130" %}
{% set raven_version = "4.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11 >=3.0.1,<4.0                 # [build_platform != target_platform]
    - cmake >=3.26.1
    - make  # [not win]
    - ninja >=1.11.0  # [win]
  host:
    - python
    - hatch-fancy-pypi-readme >=25.1.0
    - hatchling >=1.27.0
    - libnetcdf <4.10
    - pip >=25.2
    - pybind11 >=3.0.1,<4.0
    - scikit-build-core >=0.12
    - setuptools-scm >=9.2
    - zlib
  run:
    - python
    - libnetcdf <4.10.0
    - zlib

test:
  imports:
    - raven_hydro
  requires:
    - pip >=25.2
    - python
  commands:
    - pip check
    - test -f $PREFIX/bin/raven  # [not win]
    - raven -v

about:
  home: https://raven.uwaterloo.ca
  dev_url: https://github.com/Ouranosinc/raven-hydro
  doc_url: https://raven.uwaterloo.ca/files/v{{ raven_version }}/RavenManual_v{{ raven_version }}.pdf
  doc_source_url: https://raven.uwaterloo.ca/Downloads.html
  license: Apache-2.0 and Artistic-2.0
  license_file:
    - LICENSE
    - RavenHydroFramework/LICENSE
  summary: |
    The Python-based installer for the hydrological modelling framework, Raven,
    developed at the University of Waterloo in Ontario, Canada.

extra:
  recipe-maintainers:
    - Zeitsperre
    - julemai
    - huard
