{% set name = "raven-hydro" %}
{% set version = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://raven.uwaterloo.ca/files/v{{ version }}/RavenSource_v{{ version }}.zip
  sha256: 532db73a5ee0a0aa875947efb4c91b7584b7677b6d706968ea5c2d607853be67
  patches:
    - 0001-fix-makefile.patch  # [not win]

build:
  number: 0
  script:
    - make  # [not win]
    - cp ./raven $PREFIX/bin/raven  # [not win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - libnetcdf
    - make  # [not win]
  host:
    - libnetcdf
  run:
    - libnetcdf

test:
  commands:
    - test -f $PREFIX/bin/raven  # [not win]
    - raven -v

about:
  home: http://raven.uwaterloo.ca/
  dev_url: https://chyms.nrc.gc.ca/
  doc_url: http://raven.uwaterloo.ca/files/v{{ version }}/RavenManual_v{{ version }}.pdf
  doc_source_url: http://raven.uwaterloo.ca/Downloads.html
  license: Artistic-2.0
  license_file: LICENSE
  summary: The conda-forge binary for the Raven hydrological model developed at the University of Waterloo in Ontario, Canada.

extra:
  recipe-maintainers:
    - huard
    - Zeitsperre
    - julemai
